kind: Service
apiVersion: v1
metadata:
  name: domainsale-svc-v1
spec:
  selector:
    app: domainsale-app-v1
  type: ClusterIP
  ports:
  - name: https
    protocol: TCP
    port: 5000
    targetPort: 443