kind: Service
apiVersion: v1
metadata:
  name: domainsale-svc-v2
spec:
  selector:
    app: domainsale-app-v2
  type: ClusterIP
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
